apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: spring-boot-external-properties
    files:
      - application.properties
resources:
  - deployment.yaml
  - spring-boot-test-external-config-svc.yaml
  - spring-boot-test-external-config-route.yaml
